#!/bin/bash

# Master script to run all generated ImageMagick group scripts.
# Generated by Flambient Laravel Application

echo "Starting Flambient processing for all groups..."

echo "Processing Group 1..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_01_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 1 completed successfully."
else
    echo "  ✗ Group 1 failed!" >&2
fi

echo "Processing Group 2..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_02_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 2 completed successfully."
else
    echo "  ✗ Group 2 failed!" >&2
fi

echo "Processing Group 3..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_03_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 3 completed successfully."
else
    echo "  ✗ Group 3 failed!" >&2
fi

echo "Processing Group 4..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_04_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 4 completed successfully."
else
    echo "  ✗ Group 4 failed!" >&2
fi

echo "Processing Group 5..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_05_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 5 completed successfully."
else
    echo "  ✗ Group 5 failed!" >&2
fi

echo "Processing Group 6..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_06_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 6 completed successfully."
else
    echo "  ✗ Group 6 failed!" >&2
fi

echo "Processing Group 7..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_07_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 7 completed successfully."
else
    echo "  ✗ Group 7 failed!" >&2
fi

echo "Processing Group 8..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_08_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 8 completed successfully."
else
    echo "  ✗ Group 8 failed!" >&2
fi

echo "Processing Group 9..."
magick -script "/Users/davepeloso/Projects/terminal-flazsh/storage/flambient/6546/scripts/group_09_script.mgk"
if [ $? -eq 0 ]; then
    echo "  ✓ Group 9 completed successfully."
else
    echo "  ✗ Group 9 failed!" >&2
fi

echo "All groups processed."